### Create
POST http://localhost:3000/api/orders/
Content-Type: application/json

{
  "name": "Test orders",
  "description": "This is a test item"
}

###

### Get All
GET http://localhost:3000/api/orders/

###

### Get by ID
GET http://localhost:3000/api/orders/1

###

### Update
PUT http://localhost:3000/api/orders/1
Content-Type: application/json

{
  "name": "Updated orders",
  "description": "Updated description"
}

###

### Delete
DELETE http://localhost:3000/api/orders/1